server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /stock-trade
  port: 8080

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://${MONGO_HOST}/seng468

redis:
  host: ${REDIS_HOST}
  port: 6379

security:
  #  One day in MS
  expiry-ms: 86400000
  secret: ${JWT_SECRET}
