server:
  servlet:
    context-path: /stock-trade

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI}

security:
  #  One day in MS
  expiry-ms: 86400000
  secret: ${JWT_SECRET}