server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /stock-trade
  port: 8080

redis:
  host: localhost
  port: 6379
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI}

security:
  #  One day in MS
  expiry-ms: 86400000
  secret: ${JWT_SECRET}
